### ISSUE TITLE
Code review 10-9

### ISSUE THREAD

**Issue by lecondon** [hydroframe/PF_Model_Evaluation#1]
Hi Vineet, 

Wow I really love all the progress you made! I have some detailed  comments. I'm just going to leave them here by line number because I'm not sure how to do review comments unless there is a pull request. Let me know if there is a bette way to do this i in the future. 

- line 48 and line 69: I think this is a slick way to do this and we don't have to loose that but I also want to provide a more straight forward example where a user can just specify the starting and ending file number that  they would like  to use. My idea for this is in the script I pushed last time. I think you can keep this here but we should have a commented version or or other option so that people can easily see  how to just select a subset to run. 

- 60 & 61: The structure of this is a little confusing to me. Why not just do np.zeros(nt,) I ask only because again I think this will be an example that people will want to duplicate and write on their own and we want to make it as simple as possible. 

- 75/76: I would do  any manipulation of the mask inside the function. If the user provides a mask that is written out by the parflow run then they should not need to do any additional hand manipulation to get this to work

- line 80 & 86 I think we talked about making a total surface and total subsurface storage calculation too right? So that could just be a function? 

- With respect to overland flow I think this is good and there are two additional things we are going to want (other than the kinematic option)
1) the ability to get the total outflow (i.e just summing flow on the edges pointing out)
2) the ability to calculate overland flow at a point. Technically we can do this by grabbing a point out of what you calculated but the better approach would be to use the new parflowio capabilites to only read in the slope and pressure values at the point we want to do the calculation. (This will also be really good for getting WTD at a point)

Happy to discuss any of this further. Especially the last two  points might be  good to talk about. 

Thanks!

**Comment by vineetbansal** [comment]
Merged changes to master as per PR #3
