### ISSUE TITLE
Problem with WTD calculation when bottom layer pressure is negative

### ISSUE THREAD

**Issue by aktriplett** [hydroframe/PF_Model_Evaluation#11]
I have noticed in certain sections of my domain, cells where the pressure in the bottom layer is negative are resulting in calculated water table depths that are very shallow. This means that in WTD plot outputs, there appear to be sections with WTD of 1-2m adjacent to sections with WTD greater than 300m.  I'm not sure if the WTD calculation accounts for this, where if pressure in the bottom layer is negative, WTD should be set to the total depth of the domain. I can provide images if needed.

**Comment by vineetbansal** [comment]
Thanks @aktriplett ..the WTD calculation at any column is essentially:
1) Take the depth of the first layer from the top that is fully saturated
2) Subtract the pressure at this layer (the "ponding depth")

I took the implementation directly from a function written by @junzhang55. It seems to me that a low WTD would result by subtracting a large -ve value in step (2) above, which would seem to imply that in your case the saturated layer is the bottom-most, with a -ve pressure. I'm not sure about the correct hydrological thing to do in this case, but perhaps if you can send me a `.pfb` file illustrating this I can run this by @lecondon etc.?

**Comment by reedmaxwell** [comment]
I think we need to check to make sure this calculation is never done on a cell with negative pressure.

Please excuse the brevity of this message it was sent from my iPhone

On Jan 22, 2021, at 07:14, Vineet Bansal <notifications@github.com> wrote:

﻿

Thanks @aktriplett<https://github.com/aktriplett> ..the WTD calculation at any column is essentially:

  1.  Take the depth of the first layer from the top that is fully saturated
  2.  Subtract the pressure at this layer (the "ponding depth")

I took the implementation directly from a function written by @junzhang55<https://github.com/junzhang55>. It seems to me that a low WTD would result by subtracting a large -ve value in step (2) above, which would seem to imply that in your case the saturated layer is the bottom-most, with a -ve pressure. I'm not sure about the correct hydrological thing to do in this case, but perhaps if you can send me a .pfb file illustrating this I can run this by @lecondon<https://github.com/lecondon> etc.?

**Comment by vineetbansal** [comment]
Thanks @reedmaxwell .. do you mean to say:
1. Throw an error if the calculation is ever requested on a grid that has -ve pressure in any of the cells

**Comment by vineetbansal** [comment]
Thanks @reedmaxwell .. do you mean to say:
- throw an error if the wtd calculation is requested for a cell that has -ve pressure.
- return `np.nan` or some other sentinel value for that cell if this case is encountered.
- don't subtract pressure if it is -ve and simply return the depth of the first saturated layer in such cases.

**Comment by vineetbansal** [comment]
This issue is fixed in version 1.0.1 and above. Closing this.
