### ISSUE TITLE
Running average of overland flow

### ISSUE THREAD

**Issue by vineetbansal** [hydroframe/PF_Model_Evaluation#2]
@hoangtv1899  mentioned that he's only interested in the average value of overland flow, and is running out of memory when dealing with fine time steps. For situations where just the running average of properties in needed, we can perhaps add a `running_average` function..

**Comment by lecondon** [comment]
@vineetbansal sorry I'm not sure I exactly understand what you mean. Are you meaning a running average across time? I think the the answer to the memory issue is not load only the data at the point we want and then we will not have the issue. Alliteratively we can work with daily or monthly averages but I would be cautious about a running average. Perhaps I'm miss understanding though.
