### ISSUE TITLE
Mask values currently are nan and 99999

### ISSUE THREAD

**Issue by hoangtv1899** [hydroframe/PF_Model_Evaluation#8]
During the overland flow calculation, mask values should be 0 (outside of the domain) and 1 (inside of the domain) in order to calculate correctly.

**Comment by vineetbansal** [comment]
@hoangtv1899 .. None of this code generates mask values, but only reads them. We can make our code tolerant of nans/99999 values if we need to though, so if you can clarify exactly what problem you're seeing we can sort it out.

**Comment by vineetbansal** [comment]
Mask values in all functions are internally converted to booleans depending on whether they are >0 or not. This is the behavior in version 1.0.3 and above. We have no control over the incoming mask values of course. Closing this.
